### ISSUE TITLE
requires 'six' but doesn't include it as a dependency?

### ISSUE THREAD

**Issue by groovecoder** [willkg/markus#69]
I [added markus to my project](https://github.com/mozilla/fx-private-relay/pull/109/files), but when [Circle tried to run my tests](https://circleci.com/gh/mozilla/fx-private-relay/490?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), it spat out:

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/base.py", line 315, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/app/.local/lib/python3.7/site-packages/django/core/management/base.py", line 289, in create_parser
    self.add_arguments(parser)
  File "/app/.local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 44, in add_arguments
    test_runner_class = get_runner(settings, self.test_runner)
  File "/app/.local/lib/python3.7/site-packages/django/test/utils.py", line 303, in get_runner
    test_runner_class = test_runner_class or settings.TEST_RUNNER
  File "/app/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/app/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/privaterelay/settings.py", line 16, in <module>
    import markus
  File "/app/.local/lib/python3.7/site-packages/markus/__init__.py", line 5, in <module>
    from markus.main import configure, get_metrics  # noqa
  File "/app/.local/lib/python3.7/site-packages/markus/main.py", line 12, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by willkg** [comment]
Oops--I missed something when taking out Python 2 support. I'll fix that now.

**Comment by willkg** [comment]
I'll wait a bit, but then push out a new release next week. Please let me know if you find anything else. Thanks!
